# Generated by Django 5.2.14 on 2026-06-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('edit_code', 'Edit Code'), ('generate_site', 'Generate Site'), ('fix_bug', 'Fix Bug'), ('inspect_repo', 'Inspect Repo'), ('deploy_preview', 'Deploy Preview'), ('deploy_production', 'Deploy Production')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('prompt', models.TextField(blank=True)),
                ('system_summary', models.TextField(blank=True)),
                ('result_summary', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=255)),
                ('linked_branch', models.CharField(blank=True, max_length=100)),
                ('linked_commit_sha', models.CharField(blank=True, max_length=64)),
                ('log_object_key', models.CharField(blank=True, max_length=500)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
