# Generated by Django 5.2.14 on 2026-06-03 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='agents.agenttask'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='thread_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='AgentTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='agents.agenttask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
