# Generated by Django 5.2.15 on 2026-06-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agenttask_plan_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='task_type',
            field=models.CharField(choices=[('plan', 'Plan'), ('edit_code', 'Edit Code'), ('create_resource', 'Create Resource'), ('generate_site', 'Generate Site'), ('fix_bug', 'Fix Bug'), ('inspect_repo', 'Inspect Repo'), ('deploy_preview', 'Deploy Preview'), ('deploy_production', 'Deploy Production')], max_length=32),
        ),
    ]
