# Generated by Django 5.2.14 on 2026-06-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('framework', models.CharField(choices=[('html', 'HTML'), ('vite_react', 'Vite React'), ('astro', 'Astro'), ('next_static', 'Next.js Static')], default='html', max_length=32)),
                ('template_key', models.CharField(blank=True, max_length=64)),
                ('repo_provider', models.CharField(choices=[('github', 'GitHub')], default='github', max_length=20)),
                ('repo_owner', models.CharField(blank=True, max_length=255)),
                ('repo_name', models.CharField(blank=True, max_length=255)),
                ('repo_url', models.URLField(blank=True)),
                ('repo_default_branch', models.CharField(default='main', max_length=100)),
                ('github_installation_id', models.BigIntegerField(blank=True, null=True)),
                ('github_repo_id', models.BigIntegerField(blank=True, null=True)),
                ('workspace_root', models.CharField(blank=True, max_length=500)),
                ('preview_domain', models.CharField(blank=True, max_length=255)),
                ('production_domain', models.CharField(blank=True, max_length=255)),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
