# Generated by Django 5.2.14 on 2026-06-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_developer_style',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_persona_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_persona_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_primary_language',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_style_notes',
            field=models.TextField(blank=True),
        ),
    ]
