# Generated by Django 5.2.14 on 2026-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_ai_developer_style_project_ai_persona_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(choices=[('html', 'HTML'), ('vite_react', 'Vite React'), ('astro', 'Astro'), ('next_static', 'Next.js Static'), ('django', 'Django App')], default='html', max_length=32),
        ),
    ]
