# Generated by Django 5.2.14 on 2026-06-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='starter_theme',
            field=models.CharField(choices=[('default_app', 'Default App Shell'), ('dashboard', 'Dashboard')], default='default_app', max_length=32),
        ),
    ]
