# Generated by Django 5.2.15 on 2026-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_starter_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='starter_theme',
            field=models.CharField(
                choices=[
                    ('default_app', 'Default App Shell'),
                    ('dashboard', 'Dashboard'),
                    ('list_manager', 'Flexible List Manager'),
                ],
                default='default_app',
                max_length=32,
            ),
        ),
    ]
