# Generated by Django 5.2.15 on 2026-06-04 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_starter_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('plural_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_definitions', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('project', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ResourceFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('key', models.SlugField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('email', 'Email')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('show_in_list', models.BooleanField(default=True)),
                ('show_in_form', models.BooleanField(default=True)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('relation_type', models.CharField(choices=[('none', 'No relationship'), ('foreign_key', 'Foreign key')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_relationship_fields', to='projects.resourcedefinition')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='projects.resourcedefinition')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'unique_together': {('resource', 'key')},
            },
        ),
    ]
