# Generated by Django 5.2.15 on 2026-06-05 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_default_ai_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('operator_approved', 'Operator Approved'), ('shared', 'Shared')], default='private', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_widgets', to='projects.project')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WidgetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('manifest_json', models.JSONField(blank=True, default=dict)),
                ('config_schema_json', models.JSONField(blank=True, default=dict)),
                ('permissions_json', models.JSONField(blank=True, default=dict)),
                ('source_html', models.TextField(blank=True)),
                ('source_css', models.TextField(blank=True)),
                ('source_js', models.TextField(blank=True)),
                ('source_bundle_path', models.CharField(blank=True, max_length=500)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('quarantined', 'Quarantined')], default='draft', max_length=24)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_widget_versions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_widget_versions', to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.widgetdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('widget', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WidgetReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('quarantined', 'Quarantined'), ('disabled', 'Disabled'), ('re_enabled', 'Re-enabled')], max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widget_review_events', to=settings.AUTH_USER_MODEL)),
                ('widget_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='projects.widgetversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WidgetInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('homepage_top', 'Homepage Top'), ('homepage_bottom', 'Homepage Bottom'), ('sidebar', 'Sidebar'), ('footer', 'Footer')], default='homepage_top', max_length=40)),
                ('title_override', models.CharField(blank=True, max_length=200)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_widgets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_installations', to='projects.project')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='projects.widgetdefinition')),
                ('widget_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='projects.widgetversion')),
            ],
            options={
                'ordering': ['placement', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='widgetdefinition',
            name='current_approved_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.widgetversion'),
        ),
    ]
