# Generated by Django 5.2.15 on 2026-06-05 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_supportthread_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportthread',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_threads', to='projects.project'),
        ),
    ]
