# Generated by Django 5.2.15 on 2026-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_supportthread_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='support_widget_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='project',
            name='support_widget_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
