# Generated by Django 5.2.15 on 2026-06-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_inboundmessage_inboundattachment_inboundagentrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerPainQuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='manager_spreadsheet_pain_validation', max_length=120)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('respondent_email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('role_title', models.CharField(blank=True, max_length=200)),
                ('responses_json', models.JSONField(blank=True, default=dict)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
