# Generated by Django 5.2.15 on 2026-06-08 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_managerpainquestionnaireresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('paused', 'Paused'), ('former', 'Former')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=200)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='central_clients', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'external_key'), ('project', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CentralDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='central_departments', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'external_key'), ('project', 'slug')},
            },
        ),
    ]
