# Generated by Django 5.2.15 on 2026-06-09 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_centralclient_centraldepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('primary_contact_name', models.CharField(blank=True, max_length=200)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='projects.centralclient')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('client', 'external_key'), ('client', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CentralDepartmentClientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('owner', 'Owner'), ('operator', 'Operator'), ('viewer', 'Viewer'), ('partner', 'Partner'), ('other', 'Other')], default='operator', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='projects.centralclient')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='projects.centraldepartment')),
            ],
            options={
                'ordering': ['department__name', 'client__name'],
                'unique_together': {('department', 'client')},
            },
        ),
        migrations.CreateModel(
            name='CentralLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('location_type', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(blank=True, max_length=80)),
                ('primary_contact_name', models.CharField(blank=True, max_length=200)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='projects.centralorganization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'external_key'), ('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CentralTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('lead_name', models.CharField(blank=True, max_length=200)),
                ('lead_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='projects.centraldepartment')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('department', 'external_key'), ('department', 'slug')},
            },
        ),
    ]
