# Generated by Django 5.2.15 on 2026-06-09 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_centralorganization_centraldepartmentclientlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralClientDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('department_type', models.CharField(blank=True, max_length=80)),
                ('manager_name', models.CharField(blank=True, max_length=200)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_departments', to='projects.centrallocation')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('location', 'external_key'), ('location', 'slug')},
            },
        ),
    ]
