# Generated by Django 5.2.14 on 2026-06-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_notes_directives'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='context_cache',
            field=models.TextField(blank=True, help_text='Cached project context for wizard'),
        ),
        migrations.AddField(
            model_name='project',
            name='context_cache_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
