# Generated by Django 5.2.14 on 2026-06-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_context_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hugo_theme',
            field=models.CharField(blank=True, help_text='Hugo theme name (for Hugo framework projects)', max_length=128),
        ),
    ]
