# Generated by Django 5.2.14 on 2026-06-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_add_hugo_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referred_by', models.CharField(blank=True, default='direct', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
