# Generated by Django 5.2.14 on 2026-06-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('preview', 'Preview'), ('production', 'Production')], max_length=20)),
                ('slug', models.SlugField()),
                ('domain', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('deploy_path', models.CharField(blank=True, max_length=500)),
                ('web_root', models.CharField(blank=True, max_length=500)),
                ('install_command', models.CharField(blank=True, max_length=255)),
                ('build_command', models.CharField(blank=True, max_length=255)),
                ('output_directory', models.CharField(blank=True, max_length=255)),
                ('runtime_kind', models.CharField(choices=[('static', 'Static'), ('node_static', 'Node Static')], default='static', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('agent', 'Agent'), ('manual', 'Manual'), ('system', 'System'), ('git_push', 'Git Push')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('git_branch', models.CharField(blank=True, max_length=100)),
                ('git_commit_sha', models.CharField(blank=True, max_length=64)),
                ('git_commit_message', models.TextField(blank=True)),
                ('artifact_object_key', models.CharField(blank=True, max_length=500)),
                ('build_log_object_key', models.CharField(blank=True, max_length=500)),
                ('deploy_log_object_key', models.CharField(blank=True, max_length=500)),
                ('manifest_object_key', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='projects.project')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments_triggered', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='deployments.environment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
