# Generated by Django 5.2.14 on 2026-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='app_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='healthcheck_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='environment',
            name='python_entrypoint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='environment',
            name='runtime_kind',
            field=models.CharField(choices=[('static', 'Static'), ('node_static', 'Node Static'), ('django', 'Django')], default='static', max_length=20),
        ),
    ]
