# Generated by Django 5.2.14 on 2026-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_environment_app_port_environment_healthcheck_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
