# Generated by Django 5.2.14 on 2026-06-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_deployment_metadata_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
