# Generated by Django 5.2.14 on 2026-06-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_deployment_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='deploy_log_object_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
