# Generated by Django 5.2.14 on 2026-06-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_environmentvariable'),
        ('deployments', '0006_customdomain'),
    ]

    operations = [
    ]
